services:
  backend:
    image: mhieu100/vaxsafe-backend:latest
    container_name: vaxsafe-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - VNPAY_RETURN_URL=https://backend.mhieu100.space/payments/vnpay/return
      - BLOCKCHAIN_URL=http://host.docker.internal:4000/api
      - CORS_ALLOWED_ORIGINS=https://safevax.mhieu100.space
      - APP_BASE_URL=https://backend.mhieu100.space
    env_file:
      - .env
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  db:
    image: postgres:15-alpine
    container_name: vaxsafe-db
    environment:
      - POSTGRES_DB=dapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: