services:
  backend:
    image: mhieu100/vaxsafe-backend:latest
    container_name: vaxsafe-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dapp
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - VNPAY_RETURN_URL=https://backend.mhieu100.space/payments/vnpay/return
      - CORS_ALLOWED_ORIGINS=https://safevax.mhieu100.space
      - APP_BASE_URL=https://backend.mhieu100.space
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE=profile,email
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI=https://backend.mhieu100.space/login/oauth2/code/{registrationId}
    env_file:
      - .env
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  db:
    image: pgvector/pgvector:pg15
    container_name: vaxsafe-db
    environment:
      - POSTGRES_DB=dapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: