name: Blockchain Service CI/CD

on:
  push:
    paths:
      - "blockchain-service/**"
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./blockchain-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/blockchain-service:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/blockchain-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Add EC2 SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            cd ~/dev/vaxsafe-blockchain &&
            git pull origin main &&
            cd blockchain-service &&
            docker compose pull &&
            docker compose up -d &&
            docker compose logs --tail=50
          "
